# Generated by Django 5.2.10 on 2026-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Product Review', 'Product Review'), ('Product Description', 'Product Description'), ('Seller Comment', 'Seller Comment')], max_length=50)),
                ('content', models.TextField()),
                ('reported_by', models.CharField(default='AI System', max_length=100)),
                ('risk_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('ml_confidence', models.IntegerField(default=0)),
                ('recommended_action', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
