# Generated by Django 5.2.10 on 2026-02-16 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('auto_resolve_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending_approval', max_length=20)),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('risk_flag', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=20)),
                ('w9_status', models.CharField(choices=[('submitted', 'Submitted'), ('missing', 'Missing')], default='missing', max_length=20)),
                ('last_invoice_date', models.DateField(blank=True, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('coin_balance', models.IntegerField(default=0)),
                ('pending_clearance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vendor_holdings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('category', models.CharField(choices=[('sale', 'Sale'), ('payout', 'Payout'), ('fee', 'Fee'), ('refund', 'Refund'), ('installment', 'Installment'), ('service', 'Service')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('merchant_or_source', models.CharField(default='System', max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('reference_code', models.CharField(max_length=50, unique=True)),
                ('installment_plan', models.JSONField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.wallet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CoinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_history', to='payment.wallet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
